version: "3.9"

services:

  app:
    image: django-docker-prod
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn djdocker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres_db


  postgres_db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  adminer:
    image: adminer
    ports:
      - 8080:8080

  nginx:
    image: django-docker-nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  postgres-data:
  static_volume:
  media_volume: